{% set name = "cartopy" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Cartopy-{{ version }}.tar.gz
  sha256: b300f90120931d43f11ef87c064ea1dacec1b59a4940aa76ebf82cf09548bb49

build:
  error_overlinking: true
  skip: true  # [py<39]
  entry_points:
    - feature_download = tools.cartopy_feature_download.py:__main__
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - setuptools-scm >=7.0.0
    - cython >=0.29.24
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base >=3.4
    - shapely >=1.7
    - packaging >=20
    - pyshp >=2.1
    - pyproj >=3.1.0

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"
    - pip check
  requires:
    - pip

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
    - akrherz
