{% set version = "0.20.1" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-{{ version }}.tar.gz
  sha256: 91f87b130e2574547a20cd634498df97d797abd12dcfd0235bc0cdbcec8b05e3

build:
  error_overlinking: true
  number: 1
   # compatible proj and pyproj are only available for py>=37
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - proj                                   # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools-scm
    - cython
    - numpy
    - proj
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - shapely >=1.6.4
    - pyshp >=2.1
    - six >=1.3.0
    - proj
    - pyproj >=3.0
    - geos
    - matplotlib-base >=3.1
    - scipy >=0.10
    - ucrt  # [win]

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - openssl s_client -connect naturalearth.s3.amazonaws.com:443
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
    - akrherz
