{% set version = "0.16.0" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-{{version}}.tar.gz
  sha256: f23dffa101f43dd91e866a49ebb5f5048be2a24ab8a921a5c07edabde746d9a4
  patches:
    # Cartopy geos_c patch.
    - cartopy.win.patch  # [win]

build:
  skip: True  # [win and vc<14]
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - msinttypes  # [win and vc<14]
    - geos
    - proj4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - pillow
    - owslib
    - proj4
    - geos
    - shapely
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0
  license_file: COPYING
  summary: 'A library providing cartographic tools for python.'

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
